server:
  port: 8083
spring:
  rabbitmq:
    host: 192.168.150.102
    port: 5672
    virtual-host: /
    username: itcast
    password: 123456
  application:
    name: orderservice
  datasource:
    url: jdbc:mysql://localhost:3306/test02?useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  type-aliases-package: com.hmall.order.pojo
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
logging:
  level:
    com.hmall: debug
  pattern:
    dateformat: HH:mm:ss:SSS